name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npx ci

    - name: Run Linter
      run: npm run lint

    - name: Run Tests
      run: npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npx ci

    - name: Setup Git user and email
      run: |
        git config --global user.email "${{secrets.EMAIL}}"
        git config --global user.name "${{secrets.NAME}}"
        git remote set-url origin https://x-access-token:${{ secrets.TEMPORARY_TOKEN }}@github.com/LiviuLvu/ci-cd-devops-actions-pipeline
      
    - name: Deploy to GitHub Pages
      run: npm run deploy
